# Generated by Django 2.1.7 on 2019-03-27 02:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=300)),
                ('opponent', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
                ('numEpochs', models.FloatField()),
                ('numTurns', models.FloatField()),
                ('gameState', jsonfield.fields.JSONField()),
                ('payoffs', jsonfield.fields.JSONField()),
                ('epoch', models.FloatField()),
                ('turn', models.FloatField()),
                ('surveyID', models.CharField(max_length=300)),
            ],
        ),
    ]
